spring:
  application:
    name: people-batch
  cloud.task.initialize.enable: true
logging.level.org.springframework.cloud.task: DEBUG
datasource:
  cloudTask:
      url: jdbc:mysql://ubuntu:3306/cloud_task?useUnicode=true&characterEncoding=utf8
      username: dataflow
      password: dataflow
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  cloudTaskDemo:
        url: jdbc:mysql://ubuntu:3306/cloud_task?useUnicode=true&characterEncoding=utf8
        username: dataflow
        password: dataflow
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20